### ISSUE TITLE
<Hub> Hub 초기 데이터 설정

### ISSUE THREAD

**Issue by aerhergag00** [DevSquad10/b2b-service-platform#40]
## 제목
Hub 초기 데이터 설정

## 📝 이슈 개요  
고정된 허브 정보(17개 센터와 해당 주소) 초기 데이터 설정

## 💡 기대하는 해결 방법  

 **테스트환경에서만 Database Initialization를 권장합니다** 

허브 정보의 초기 데이터로 테스트의 편의성을 높입니다.

## 📷 참고 자료 (선택)  

application-test.yml에 해당 내용 추가
```
spring:
 jpa:
  defer-datasource-initialization: true
 sql:
  init:
   schema-locations: classpath:sql/init/schema-test.sql
   data-locations: classpath:sql/init/data-test.sql
   mode: always
```

## ⏳ 예상 작업 시간  

---

#### ⚡ 추가 정보  
- 관련 태그: `feature` 
- 담당자: 이지웅
- 우선순위: `낮음`
